org: jcford
app: jcford-portfolio-backend
service: jcford-portfolio-backend

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
